### ISSUE TITLE
evaluation of GAN train

### ISSUE THREAD

**Issue by tornadomeet** [Ldpe2G/DeepLearningForFun#1]
hello, @Ldpe2G 
what's the error of GAN-D value at the end of your training? this issue is the same to
https://github.com/tqchen/mxnet-gan/issues/7
in your https://github.com/Ldpe2G/DeepLearningForFun/blob/master/Mxnet-Scala/Gan/src/main/scala/example/GanMnist.scala#L20

**Comment by Ldpe2G** [comment]
@tornadomeet I got nearly 0.015 in the end.

**Comment by tornadomeet** [comment]
thanks, same here when training more epoch.

**Comment by tornadomeet** [comment]
@Ldpe2G btw, do you know which paper is implemented the semiGAN in mxnet-gan?   https://github.com/tqchen/mxnet-gan/blob/master/example/gan_mnist_semisupervised.py

**Comment by Ldpe2G** [comment]
@tornadomeet I know two papers about semi-supervised GAN:

"Semi-Supervised Learning with Generative Adversarial Networks". Odena A. 2016
"Improved Techniques for Training GANs". Salimans T, Goodfellow I, Zaremba W, et al. 2016

**Comment by tornadomeet** [comment]
very thanks, i found it is the second paper by openai.
