### ISSUE TITLE
Pix2Pix parameters

### ISSUE THREAD

**Issue by benqua** [Ldpe2G/DeepLearningForFun#2]
Hi,

I am playing with your Pix2Pix implementation and would like to ask you how long (or how many epoch) it took to get the model that give you the results shown in the readme for the edges2handbags data set?
Could you share the parameters you used to train the model (learning rate, # epoch, ...)?

I would also like to thank you for his repository :). This is really nice as there are not enough examples of mxnet-scala available.

**Comment by Ldpe2G** [comment]
@benqua your welcome ：）.   I think you can use the default setting in the script to see if you can reproduce the result and the training process should at least take half a day. Also the result showed on readme are selected carefully by me：）.

**Comment by benqua** [comment]
ok, will try. Thanks for your answer.
