### ISSUE TITLE
Calculate FLOPs of a given mxnet model

### ISSUE THREAD

**Issue by WIll-Xu35** [Ldpe2G/DeepLearningForFun#3]
Hi,

I'd like to use your run_calflops.sh to evaluate the FLOPs of a mxnet model. I've gone through the readme file and found myself a bit lost since I've got no experience with scala or sbt.

I've already got mxnet cuda verison, installed sbt, java jdk and scala. Could you please tell me what is my next step?

Thank you in advance.

**Comment by Ldpe2G** [comment]
Did you successfully compile the mxnet-scala package from source? and you should got the "mxnet-full_2.11-linux-x86_64-gpu-1.5.0-SNAPSHOT.jar" file in the scala-package/assembly/linux-x86_64-gpu/targe folder.

**Comment by Ldpe2G** [comment]
Then follow the build setp, you should successfully compile the project.

**Comment by Ldpe2G** [comment]
@WIll-Xu35 I open sourced the python version, you can have a try :). https://github.com/Ldpe2G/DeepLearningForFun/tree/master/MXNet-Python/CalculateFlopsTool

**Comment by WIll-Xu35** [comment]
@Ldpe2G Nice work! I'll definitely give it a try:)
