### ISSUE TITLE
group卷积计算量那块有问题？

### ISSUE THREAD

**Issue by ngunauj** [Ldpe2G/DeepLearningForFun#4]
那块如果按照你这样的算法计算的话，group卷积计算量的计算就不对了
https://github.com/Ldpe2G/DeepLearningForFun/blob/f236517d3ee5508ded6cda01c5880724156e3db0/MXNet-Python/CalculateFlopsTool/calculateFlops.py#L132
把num_group去掉就对了

**Comment by Ldpe2G** [comment]
是的，权值的形状已经考虑了分组的情况，所以是不需要再除以num_group。
感觉可能换成类似下面写法会更好理解一点，
 total_flops += input_shape[2] * input_shape[3] * input_channel * output_channel * kernel_h * kernel_w / num_group
